hero:
  broadcastPrefix: '&c[Tier 1] '
  keyName: '&5[Hero Key]'
  keyLore:
  - '&eUse this key to unlock a Hero crate!'
  - '&aJust &6right-click&a a Hero chest to open it!'
  keyEnchantment: DURABILITY:10
  keyMaterial: EMERALD
  keySound: ANVIL_USE
  crateLocations: []
  prizePackages:
    '0':
      percent: 10
      playerMessage: '&bCongratulations on opening a Hero chest!'
      broadcastMessage:
      - '&b%player% &aopened a Hero Chest!'
      - '&cBe sure to congratulate him/her when you see them!'
      commands:
      - sudo %player% me is happy!
      - msg %player% &2Congratulations on your chest opening!
    '1':
      percent: 40
      playerMessage: '&bCongratulations on opening a Hero chest, &e%player%&b!'
      broadcastMessage:
      - '&b%player% &aopened a Hero Chest and recieved tier 1 prizes!'
      - '&cBe sure to steal from him/her when you see them!'
      commands:
      - sudo %player% me is really happy with all these diamonds!
      - give %player% diamond 64
    '2':
      percent: 60
      playerMessage: '&aCongratulations! Too bad you didnt win anything good...'
      broadcastMessage:
      - '&b%player% &aopened a Hero Chest and recieved tier 2 prizes!'
      - '&cThey didnt get anything good..!'
      commands:
      - sudo %player% me is really sad with their prizes
      - give %player% dirt 5